import styles from "./styles.module.css";

import Link from "next/link";

import Image from "next/image";

import React from 'react'

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

function BlogCard({title , id, body}) {
  return (
    <Link href={`/${id}`} className={styles.card} id={id}>
        <div className={styles.cardImage}>
            <Image src={`https://picsum.photos/200/300?random=${id}`} fill alt="Blog Card"/>
        </div>
        <div className={styles.cardBody}>
            <h3>{title}</h3>
            <p>{body}</p> 
        </div>
    </Link>
  )
}

export default BlogCard