import React from 'react'

function Head() {
  return (
    <>
        <title>Next.js 13 | Blog App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico"/>
    </>
  )
}

export default Head